#!/bin/bash
cat > ~/SecUAV/docker-compose.yaml <<EOF
version: '3'
services:
EOF

i=1
droneNum=$1
while [ $i -le $droneNum ]
do
cat >> ~/SecUAV/docker-compose.yaml <<EOF
    drone$i:
        image: myubuntu:22.04
        container_name: "drone$i"
        volumes:
          - /home/rookia/SecUAV:/SecUAV
        environment:
          - LD_LIBRARY_PATH=/SecUAV/lib
        tty: true 
        stdin_open: true
        command: /bin/bash -c "cd /SecUAV && ./main && ./sleep"
        networks:
          group:
            ipv4_address: 10.10.0.`expr $i + 10`
EOF
    i=`expr $i + 1`
done

cat >> ~/SecUAV/docker-compose.yaml <<EOF
networks:
  group:
    external:
      name: group
EOF

echo "docker-compose file generate success!"

